---
name: "Refresh docs build dependencies"
"on":
  schedule:
    # Weekly
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      base-branch:
        required: false
        type: string
      pr-branch:
        required: false
        type: string
      reset-branch:
        type: boolean
        default: false
      labels:
        required: false
        type: string
  push:
    branches:
      - devel
    paths:
      - .github/workflows/reusable-pip-compile.yml
      - ".github/workflows/pip-compile-docs.yml"
      - "tests/*.in"

jobs:
  refresh:
    name: "Refresh docs build dependencies"
    uses: ./.github/workflows/reusable-pip-compile.yml
    with:
      message: "ci: refresh docs build dependencies"
      base-branch: "${{ inputs.base-branch || 'devel' }}"
      pr-branch: "${{ inputs.pr-branch || 'pip-compile/devel/docs' }}"
      nox-args: "-e 'pip-compile-3.11(requirements)' 'pip-compile-3.11(requirements-relaxed)'"
      reset-branch: "${{ inputs.reset-branch || false }}"
      labels: "${{ inputs.labels || 'doc builds,no_backport' }}"
    secrets: inherit
